DROP TABLE IF EXISTS TB_ACNT;
DROP TABLE IF EXISTS TB_TRNS_HST;
DROP SEQUENCE IF EXISTS SEQ_ACCOUNT_TRANSACTION_HISTORY;

CREATE TABLE TB_ACNT
(
  ACNT_NO	VARCHAR(20) NOT NULL,
  CSTM_ID	VARCHAR(20) NOT NULL,
  CSTM_NM	VARCHAR(20) NOT NULL,
  ACNT_NM	VARCHAR(20) NOT NULL,
  NEW_DTM	VARCHAR(20) NOT NULL
)
;
COMMENT ON TABLE TB_ACNT
  IS 'Account';
COMMENT ON COLUMN TB_ACNT.ACNT_NO
  IS 'Account Number';
COMMENT ON COLUMN TB_ACNT.CSTM_ID
  IS 'Customer ID';
COMMENT ON COLUMN TB_ACNT.CSTM_NM
  IS 'Customer Name';
COMMENT ON COLUMN TB_ACNT.ACNT_NM
  IS 'Account Name';
COMMENT ON COLUMN TB_ACNT.NEW_DTM
  IS 'Creation Date and Time';

ALTER TABLE TB_ACNT
  ADD CONSTRAINT TB_ACNT_PK PRIMARY KEY (ACNT_NO);

CREATE TABLE TB_TRNS_HST
(
  ACNT_NO	VARCHAR(20) NOT NULL,
  SEQ		INTEGER NOT NULL,
  DIV_CD		VARCHAR(1) NOT NULL,
  STS_CD  	VARCHAR(1) NOT NULL,
  TRNS_AMT	BIGINT DEFAULT 0,
  ACNT_BLNC	BIGINT DEFAULT 0,
  TRNS_BRNCH	VARCHAR(20) NOT NULL,
  TRNS_DTM	VARCHAR(20) NOT NULL
)
;
COMMENT ON TABLE TB_TRNS_HST
  IS 'Transaction History';
COMMENT ON COLUMN TB_TRNS_HST.ACNT_NO
  IS 'Account Number';
COMMENT ON COLUMN TB_TRNS_HST.SEQ
  IS 'Sequence Number';
COMMENT ON COLUMN TB_TRNS_HST.DIV_CD
  IS 'Division Code';
COMMENT ON COLUMN TB_TRNS_HST.STS_CD
  IS 'Status Code';
COMMENT ON COLUMN TB_TRNS_HST.TRNS_AMT
  IS 'Transaction Amount';
COMMENT ON COLUMN TB_TRNS_HST.ACNT_BLNC
  IS 'Account Balance';
COMMENT ON COLUMN TB_TRNS_HST.TRNS_BRNCH
  IS 'Transaction Branch';
COMMENT ON COLUMN TB_TRNS_HST.TRNS_DTM
  IS 'Transaction Date and Time';
ALTER TABLE TB_TRNS_HST
  ADD CONSTRAINT TB_TRNS_HST_PK PRIMARY KEY (ACNT_NO,SEQ);

CREATE SEQUENCE SEQ_ACCOUNT_TRANSACTION_HISTORY;