DROP TABLE IF EXISTS TB_TRNF_HST;
DROP TABLE IF EXISTS TB_TRNF_LMT;
                 
CREATE TABLE TB_TRNF_HST
(
  CSTM_ID	VARCHAR(20) NOT NULL,
  SEQ		INTEGER NOT NULL,
  DIV_CD		VARCHAR(1) NOT NULL,
  STS_CD  	VARCHAR(1) NOT NULL,
  DPST_ACNT_NO	VARCHAR(20) NOT NULL,
  WTHD_ACNT_NO	VARCHAR(20) NOT NULL,
  SND_MM	VARCHAR(100) NOT NULL,
  RCV_MM	VARCHAR(100) NOT NULL,
  RCV_CSTM_NM	VARCHAR(20) NOT NULL,
  TRNF_AMT	BIGINT DEFAULT 0,
  TRNF_DTM	VARCHAR(20) NOT NULL
)
;
COMMENT ON TABLE TB_TRNF_HST
  IS 'Transfer History';
COMMENT ON COLUMN TB_TRNF_HST.CSTM_ID
  IS 'Customer ID';
COMMENT ON COLUMN TB_TRNF_HST.SEQ
  IS 'Sequence Number';
COMMENT ON COLUMN TB_TRNF_HST.DIV_CD
  IS 'Division Code';
COMMENT ON COLUMN TB_TRNF_HST.STS_CD
  IS 'Status Code';
COMMENT ON COLUMN TB_TRNF_HST.DPST_ACNT_NO
  IS 'Deposit Account Number';
COMMENT ON COLUMN TB_TRNF_HST.WTHD_ACNT_NO
  IS 'Withdrawal Account Number';
COMMENT ON COLUMN TB_TRNF_HST.SND_MM
  IS 'Sender Memo';
COMMENT ON COLUMN TB_TRNF_HST.RCV_MM
  IS 'Receiver Memo';
COMMENT ON COLUMN TB_TRNF_HST.RCV_CSTM_NM
  IS 'Receiver Customer Name';
COMMENT ON COLUMN TB_TRNF_HST.TRNF_AMT
  IS 'Transfer Amount';
COMMENT ON COLUMN TB_TRNF_HST.TRNF_DTM
  IS 'Transfer Date and Time';
ALTER TABLE TB_TRNF_HST
  ADD CONSTRAINT TB_TRNF_HST_PK PRIMARY KEY (CSTM_ID, SEQ);

CREATE TABLE TB_TRNF_LMT
(
  CSTM_ID		VARCHAR(20) NOT NULL,
  ONE_TM_TRNF_LMT	BIGINT DEFAULT 0,
  ONE_DY_TRNF_LMT	BIGINT DEFAULT 0
)
;
COMMENT ON TABLE TB_TRNF_LMT
  IS 'Transfer Limit';
COMMENT ON COLUMN TB_TRNF_LMT.CSTM_ID
  IS 'Customer ID';
COMMENT ON COLUMN TB_TRNF_LMT.ONE_TM_TRNF_LMT
  IS 'One-Time Transfer Limit';
COMMENT ON COLUMN TB_TRNF_LMT.ONE_DY_TRNF_LMT
  IS 'One-Day Transfer Limit';
ALTER TABLE TB_TRNF_LMT
  ADD CONSTRAINT TB_TRNF_LMT_PK PRIMARY KEY (CSTM_ID);