DROP TABLE IF EXISTS TB_CSTM_CQRS;
DROP TABLE IF EXISTS TB_ACNT_CQRS;
DROP TABLE IF EXISTS TB_RCNT_WORK;


CREATE TABLE TB_CSTM_CQRS
(
  CSTM_ID    	VARCHAR(20) NOT NULL,
  CSTM_NM  	VARCHAR(100),
  CSTM_AGE 	VARCHAR(3),
  CSTM_GND 	VARCHAR(1),
  CSTM_PN   	VARCHAR(20),
  CSTM_ADR  	VARCHAR(1000),
  ONE_TM_TRNF_LMT	BIGINT DEFAULT 0,
  ONE_DY_TRNF_LMT	BIGINT DEFAULT 0	
)
;
COMMENT ON TABLE TB_CSTM_CQRS  
IS 'Customer CQRS';
COMMENT ON COLUMN TB_CSTM_CQRS.CSTM_ID  
IS 'Customer ID';
COMMENT ON COLUMN TB_CSTM_CQRS.CSTM_NM 
 IS 'Customer Name';
COMMENT ON COLUMN TB_CSTM_CQRS.CSTM_AGE  
IS 'Age';
COMMENT ON COLUMN TB_CSTM_CQRS.CSTM_GND  
IS 'Gender';
COMMENT ON COLUMN TB_CSTM_CQRS.CSTM_PN 
IS 'Phone Number';
COMMENT ON COLUMN TB_CSTM_CQRS.CSTM_ADR  
IS 'Address';
COMMENT ON COLUMN TB_CSTM_CQRS.ONE_TM_TRNF_LMT  
IS 'One-Time Transfer Limit';
COMMENT ON COLUMN TB_CSTM_CQRS.ONE_DY_TRNF_LMT  
IS 'One-Day Transfer Limit';
ALTER TABLE TB_CSTM_CQRS
  ADD CONSTRAINT TB_CSTM_CQRS_PK PRIMARY KEY (CSTM_ID);

CREATE TABLE TB_ACNT_CQRS
(
  ACNT_NO	VARCHAR(20) NOT NULL,
  CSTM_ID	VARCHAR(20),
  ACNT_NM	VARCHAR(20),
  NEW_DTM	VARCHAR(20),
  ACNT_BLNC	BIGINT DEFAULT 0
)
;
COMMENT ON TABLE TB_ACNT_CQRS
  IS 'Account CQRS';
COMMENT ON COLUMN TB_ACNT_CQRS.ACNT_NO
  IS 'Account Number';
COMMENT ON COLUMN TB_ACNT_CQRS.CSTM_ID
  IS 'Customer ID';
COMMENT ON COLUMN TB_ACNT_CQRS.ACNT_NM
  IS 'Account Name';
COMMENT ON COLUMN TB_ACNT_CQRS.NEW_DTM
  IS 'Creation Date and Time';
COMMENT ON COLUMN TB_ACNT_CQRS.ACNT_BLNC
  IS 'Account Balance';
ALTER TABLE TB_ACNT_CQRS
  ADD CONSTRAINT TB_ACNT_CQRS_PK PRIMARY KEY (ACNT_NO);
  
CREATE TABLE TB_RCNT_WORK
(
  CSTM_ID    	   VARCHAR(20) NOT NULL,
  CSTM_NM  	      VARCHAR(100),
  RCNT_WORK_DIV_CD 	VARCHAR(1),
  RCNT_WORK_DTM	   VARCHAR(20),
  WORK_ACNT_NO   	   VARCHAR(20),
  WORK_TRNS_AMT  	   BIGINT DEFAULT 0,
  WORK_STS_CD 	      VARCHAR(1)
)
;
COMMENT ON TABLE TB_RCNT_WORK
IS 'Recent Work';
COMMENT ON COLUMN TB_RCNT_WORK.CSTM_ID  
IS 'Customer ID';
COMMENT ON COLUMN TB_RCNT_WORK.CSTM_NM 
 IS 'Customer Name';
COMMENT ON COLUMN TB_RCNT_WORK.RCNT_WORK_DIV_CD  
IS 'Recent Work Division Code';
COMMENT ON COLUMN TB_RCNT_WORK.RCNT_WORK_DTM  
IS 'Recent Work Date and Time';
COMMENT ON COLUMN TB_RCNT_WORK.WORK_ACNT_NO
IS 'Work Account Number';
COMMENT ON COLUMN TB_RCNT_WORK.WORK_TRNS_AMT 
IS 'Work Transaction Amount';
COMMENT ON COLUMN TB_RCNT_WORK.WORK_STS_CD 
IS 'Work Status Code';
ALTER TABLE TB_RCNT_WORK
  ADD CONSTRAINT TB_RCNT_WORK_PK PRIMARY KEY (CSTM_ID);